# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:74J45z0n4g1JzLxxjseN/8JVJADU+JqfMqLe8YEfucVbaknhQe93CfFDzjJTYghVW6K4yRnLQ/bgsU156x/zCflLjVYQmq+BwFQo4x1kYo0tZuaDBoo4rIu8hgLQNhYmYErw+bYVVxXJAsu1Ub2596Owhm7mKCwYlDf9XIfNVsCtrtU3o1J9yloeVpqIGMV5BUPL+pMwtYdQyGfKnYaerG7LGLbo9bNKQpbYGuBAmnQnpFmYFA==,iv:YaYm3F3b1n2xV9i0pzhebdyP09Pd394FsoywlAP49S4=,tag:ysEPVfMBqSzXC/jdSQMOig==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXc2xkNDd1eTM3UUdMdlBv
        cTU0VUd3S1l5NnR2UUVVLzErMCtWV0FyelZFCnRUNEQyY3kvZWZ1TGRHSFFRZ0dS
        MnRzRHhpRE4rNkZpcldQV1lEOHlaZUkKLS0tIG5OMXRVMG9EZlppNnVyN1J2RHZB
        bzBCcElZbFlvR29ZcS96VlVBY3NBREkKWOeiyVda2LBkO/SV6J12Fx/banNDclNd
        hwvCaa29b3cWwfrdsvBdu6/p9kV4czXXti8KNd3TtjS/Y1GLzzEUAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-30T14:41:33Z"
  mac: ENC[AES256_GCM,data:eyVKzn3dPVRH0U1s1ffJJTEGqot103F+MXSbWrTzGPifnUFASpOEm3DiaPSxI9woByvLDP3LCfpQzI32tKSC5EYo6bj9+/+iGQGSUlNQMt3nv2KxazYRhC7R3POaaafpu8wRLMcwaH0LNTLYSyvSnsMDRtg+9490tidzudZ64g8=,iv:Piv+afsnr6uyIJ6FwlaGvc+FbZbfm0RPl7JMfXxIZgw=,tag:OxSmCR4xeL8KGoDgjV1IgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
