# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wY7VmYaQtMjyTs53StUYWGD08pY9nqDtX8oPPUX4rqaTreX4CLZH7fEkqJw7rVIopPw80+b34UhtbGP0MspRMOK0k+KW8Vw9qDbk504TM4OF/Uwa5jB2XhRQEtZIMK7oIn+NqBDi7m1YXBVZyFDVVg40ZnEtpAiZz3sxAtLrcI+2tlGWOu+NcoSnsaV53a+DCSWgf/cuPpiQ6V8ENIrYvJ8obUSgN25aY7cfrJQCR9RirAck6A==,iv:I9QU3ZNYkI8Cl/i0l04gjiDU6PebPdI0HBlPhFZLOxc=,tag:8meq+j3pJaRaOr/p0rvzwg==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Skt3U0N6SzVCNzFia1Yw
        akxFU0lkMUIwNC92TzZmOTVacGJEd2JjVXkwCkp5RVB3SUJRZGowU3lsL3o4RnJF
        OGwxSWJZVFNDemRmRGJBZXFsSUlLN3MKLS0tIHBzcmk4eDBHSUYrYlN0dFlQODMz
        THEwOEV6ZVNvSEx1QnA0cXpuNmYvRkkKJMPNYGCqoerUEHXbo+DjAFAwhYeSjTni
        Lm7aBeOaNvJ6QuxWTGALUqwtkiaVMHhQQaLfHtmlgCNLIgA3syOH5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-30T15:10:24Z"
  mac: ENC[AES256_GCM,data:uDGhMn90hqsy8RjkkAkrH4htRDhHmsduOHnR/kyq6YGzvSoCvMJs1uHGaDaoSTJKpYiZnOkDvD0kd/GyqGWKyy//21Jdb3yguPE2TMwYoqrD9eNdNWMK3xNYEZg6tSG+QJPy5RblmEpPVK8faz1vHPyvvpxcp8+kbnyzvvm2nPk=,iv:utGkRW0p8/idf3ZJQLgO4DOekRvwQG8uBbFXiHgU6cI=,tag:Edae6XWur0RMVnr4zfDHtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
