# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3k0bYGXeZiNUZXtWF5cjF8jkRu9uTGjiMpLMQyeNLEr92+F5oTpkuA==,iv:drgCF7bh5Q3ypXyDb6ysL7kvmYofW95DO8SqX2dg2nk=,tag:JcBxLYZ//q3/V1hZftxoGA==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVTV6QVloVHlHMEdRejRk
        MUhRMWdJS3pHcVZTcmZXdHlyYzRSWDFJb1NBCkpZVmxDWUcxY1l2OWhBVGNwZE1v
        RFhFd21oNUgya1h6T2gwZEdpcmxpQ3MKLS0tIHRrNjNyWXdhTEVXL0d2QmhpMERF
        aGEvV284eTIzVFBvOEZMZEFjZUVDLzAKzUr/QvT93Erj1xpxOkS8eqzLzKpMHF2i
        rwqKr0MppTN6pJAAgG30z1bTK3m2UFm+z6YXdRxbOYz589dxEhkx9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T13:07:02Z"
  mac: ENC[AES256_GCM,data:XuJU5bC9PxJRxk49PoLFQZX9sUK45nYhGPorI/57yu0FgCQNlnQAN1JvZdvK0fHYueOxIYla6y5lCBWgkQ4nubGvWwt0pKOE7H/Vl7mpgQlefq/0zRGNxoTTLh5e4y8c4F0YZEmv9Z9DJJCeY1LvKzDTQuQsfBENqBjcJ7kDXqA=,iv:os7JSYgQUmkzPboT/FPqVtLuoowY18UqgUgWjm0eKwE=,tag:LEjg3KytCUQW80NTz2wJ/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
