# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3pMd+5vdPwT4dzbaa4/y9tGOJcE8+VXs+UhAub7OhjYCYCyadEU3IA==,iv:v67pYGBXacsZYWxMSsAD8HXVQ+XNagl5aSwZX9jdYq0=,tag:xQbEQIRKmxZieThwyii2Gw==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbGRCazUvejM2Y0paSyt0
        dkRhTW54ZnBEMVBCckhKKytRMWsyVmtGTUVvCm9kS1JzcktOQ0xqS1lrbXJHNkt5
        dnR4Q28xQ3ZLSXlDT0ltQm9Ib25CNDAKLS0tIEY2NzA5NG9Ib04zTWJxcGxRY1pn
        ZEoyZUk5UTI3Mytua282V29iblJQTjgKWre19JRMEcBvmf8Z3o4xdQo53v/j82/n
        PWzAk/DM0pCzhNyCph5FoIrqifKm865IFW12Ti1+LqwMIP5QgWKu0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T09:28:11Z"
  mac: ENC[AES256_GCM,data:DSsqH0SxKNiSrV0dT4WK5Kfjizp5U561UnolEa37faX1bA9eyPKzhrl0OqEuBUbSfiPA+4+j3ZOz84Ks45DGvmrzvt0r2vwuuEr+im79FTFyXCx1oWsCLNE2H9r6ixfvdTdr5YGlUSdNyFNIPp0aEQohmS1rn5Aq7EQTobqVUPs=,iv:AOumaSJW0VZ7HvhxaCT8iUxisQGV8TPCFVspVVT1hGU=,tag:J+MyIh/uUNu87MyoAw67qQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
