# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:oEzdRZMHbphBt/JlDrTLFa8owExVLf6Gzu9+9iWfdjDcPSmUj+SuVg==,iv:fFUEPHDCF/nPLMWSBNPD6UNSxFdPaViyctOCIl9WOwU=,tag:j+iqQg2ssNnZvFvDUloz7A==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNDB3ZFlwY2l6cC9nOC9M
        NldNKzJvTHNSMnRBMVZqY2UwbFYxMi9yYWdjCkcwUjJnOUJOWnVmU2pEbUtFVlFS
        M0Y3OEdQTmtEU29EclgvVjQ3RVY4clkKLS0tIExFd0RyalJYcGVucEx2bmxVRVBE
        L3BrUWtDd1RITHNOVU0xUWFRQnMxbVEKSq5etcatrbRkrONbGYRhgGuDXFMbDgGZ
        Pb1el1QueryMbtiCmVeHQd/Vba7QnyDmoVErsgCuHFJnFb2gWrnMvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T09:31:28Z"
  mac: ENC[AES256_GCM,data:uV0jSQUOZmKMc9uopsxvl5SaRveD9dw7cioOkcaadWgfPpjPgnKWnxfzK5UZRMqd2fUbuUOVxXTWYVvVxiRgzxBhJNuep1QLN6ts5HnJpegs31AzbwVRge31xVbDTkpjot7QiZktjIwQrrk7z1LKdX+hvTRTNv7dTaJreh4ZycA=,iv:wgeu0ufQ3xCjmI2fFnv2dSW5xE8rS3zC/dp6NT5T9z8=,tag:WxQ3lWslYcWUO0AG5h+nWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
