# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BmOTf9iuVR8ROwu3zHQoMQThynL6u54pe8sBtQu6fITXWUG3k97avA==,iv:fPVX51XK16cxPda8m5GMpcfKia41djRVS3vPGOxzyws=,tag:WGVl3VFunfKrMbsLzGWqeA==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLclhTUys2dDhDc1YrRUox
        a3B1NTBrUkMvRkNyVjM1UjArZHRtcGZJSzBrCkU5Q0VaUk5CMXRSZUszUEw2QTJR
        VDJHd2FvTFBwSm9nUFVpS2Z1K2dDUzgKLS0tIGFJQ0toNFp3UGxZaWZFY09PQURE
        ck8rWjNObGNyY081N3JOV3FEeDBSVUkKoE+X2K72fXxEoIfRB5kOPNMJlY7ynYgz
        XO+PPBvUYazR3F0pMdseqRH25RZopBwh45c2b1PraSyrrDO4QF4OUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T11:09:48Z"
  mac: ENC[AES256_GCM,data:HxjEEWlFCduRB9fFOuKm1JPZOX+LPUSU/6S98qZi06Y7goYfQbvEw9hapgvxvNhmH1cOonXMIGBUSv0T1A84XwPd2+E5xdiwmTjmpAYN9P/bJiKtm30W5kva//wPNd5s/lCXdxBkol4UPck0Gf+m/ofgDnVVU8W9mPRERT+aFMw=,iv:UH8SRnA8xYD4hRaewTc9eNb+VgusuO/HrWPesw634tY=,tag:w9riJ/g5q1D/Gb2P+cl8iA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
