# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: plex-media-server
spec:
  interval: 1m
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      # Specify a chart version here for stability.
      # Find available versions on Artifact Hub: https://artifacthub.io/packages/helm/gabe565/plex
      version: "0.5.1" # <<--- Specify a version here! (Good job setting this!)
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: plex-media-server
  values:
    # --- Configured Values for gabe565/plex chart ---
    # Based on default values and your requirements.
    # Consult the full chart values.yaml or documentation for advanced options.

    image:
      repository: ghcr.io/linuxserver/plex
      pullPolicy: IfNotPresent
      # tag: "version-1.41.4.9463-630c9f557" # Uncomment and set a specific tag if needed

    env:
      TZ: "Europe/Prague" # <<--- Set your timezone
      # Add other required environment variables for linuxserver/plex here
      # PUID and PGID are often required for file permissions
      # Find your user/group ID on the node that will access your media files
      # PUID: "1000" # Example PUID - **UNCOMMENT AND SET THIS**
      # PGID: "1000" # Example PGID - **UNCOMMENT AND SET THIS**
      # VERSION: "docker" # Often required for linuxserver images

    # hostNetwork is correctly omitted/false here, using standard networking
    # hostNetwork: false

    # dnsPolicy is correctly omitted/defaulting to ClusterFirst
    # dnsPolicy:

    service:
      main:
        enabled: true
        ports:
          http: # This name 'http' corresponds to the port definition below
            enabled: true
            port: 80 # This is the SERVICE port - the port the Service listens on
            # targetPort: This is the port your application listens on inside the pod.
            # If not specified, it defaults to 'port'. For Plex, 32400 is usually both.
            # targetPort: 32400 # <--- Often explicitly set, though defaults to 'port' if omitted
        # --- Alternative: Use LoadBalancer Service Type for direct external access ---
        # type: LoadBalancer # <<--- Uncomment this AND comment out type: ClusterIP above for a LoadBalancer
        # annotations: {} # Add LoadBalancer specific annotations here if needed (e.g., for MetalLB IP allocation)
        # For MetalLB, you might need annotations like:
        # annotations:
        #   metallb.universe.tf/address-pool: your-address-pool-name

    ingress:
      main:
        enabled: true # Set to 'false' if you only want the LoadBalancer service
        primary: true
        ingressClassName: internal # <--- Ensure you have an Ingress Controller installed that handles this class
        hosts:
          - host: plex.${SECRET_DOMAIN} # <--- Ensure SECRET_DOMAIN is replaced or handled by Flux
            paths:
              - path: /
                pathType: Prefix
                service:
                  # 'name' should match the actual name of the Service created by the chart (likely 'plex')
                  name: plex
                  # 'port' must match the Service's 'port' (the one the Service listens on), NOT the targetPort
                  port: 80 # <--- Must match service.main.ports.http.port above

      tls:
        enabled: true # Set to 'false' if you don't want TLS via Ingress
        # The secret MUST exist in the namespace and contain valid TLS certs for the host
        secretName: plex-tls # <<--- Name of the TLS secret (ensure it exists!)
        # If using cert-manager to auto-create the secret, uncomment and configure the issuer annotation
        # annotations:
        #   cert-manager.io/cluster-issuer: "letsencrypt-production" # <--- Uncomment if using cert-manager

    # --- Persistence Configuration is CRITICAL for Plex ---
    # The chart documentation will show the 'persistence' section.
    # You NEED to configure persistent volumes for:
    # 1. The Plex configuration directory (/config)
    # 2. Your media libraries (e.g., /tvshows, /movies)
    # If these are not configured or misconfigured, Plex will not start correctly,
    # which would cause the Service/Ingress to return a 503.
    # persistence:
    #   config:
    #     enabled: true
    #     storageClass: your-storage-class # <--- Set your storage class
    #     size: 10Gi # Adjust size as needed
    #   media: # Example for media, consult chart docs for exact structure
    #     enabled: true
    #     type: hostPath # Or PVC, NFS, etc.
    #     hostPath: /path/to/your/media # <--- Set the actual path on your node(s)
    #     mountPath: /data # <--- Set the path where media is mounted in the pod

    # --- Probes ---
    # Ensure probes are configured and targeting the correct port (targetPort: 32400)
    # The chart defaults usually handle this correctly if the service port is right.
    # probes:
    #   liveness:
    #     spec:
    #       port: 32400 # <--- Ensure this matches the application's listening port
    #   readiness:
    #     spec:
    #       port: 32400 # <--- Ensure this matches the application's listening port
    #   startup:
    #     spec:
    #       port: 32400 # <--- Ensure this matches the application's listening port

    # ... rest of the values ...