# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  url: https://k8s-home-lab.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  chart:
    spec:
      chart: plex
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex-media-server
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Prague
    persistence:
      config:
        enabled: true
        isPvc: true
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Gi
      data:
        enabled: true
        isPvc: true
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 500Gi
    service:
      enabled: true
      type: ClusterIP
      port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - plex.${SECRET_DOMAIN}
            secretName: plex-tls