# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  url: https://utkuozdemir.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  chart:
    spec:
      chart: plex
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex-media-server
  values:
    serviceAccount:
      create: false

    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 2Gi

    data:
      enabled: true
      storageClass: openebs-hostpath
      size: 500Gi

    service:
      enabled: true
      type: ClusterIP
      port: 32400
      targetPort: 32400

    ingress:
      enabled: true
      className: internal
      pathType: Prefix
      hosts:
        - host: plex.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - plex.${SECRET_DOMAIN}
          secretName: plex-tls
      certManager:
        enabled: true
        issuerRef:
          name: letsencrypt-production
          kind: ClusterIssuer

    extraVolumeMounts:
      - name: config
        mountPath: /config
      - name: plex-data
        mountPath: /data
