# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1m
  url: https://utkuozdemir.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 5m
  chart:
    spec:
      chart: utkuozdemir
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex-media-server
  values:
    image:
      repository: docker.io/linuxserver/plex
      pullPolicy: IfNotPresent
    service:
      controller: plex
      ports:
        http:
          port: 80
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: plex.${SECRET_DOMAIN}
          paths:
            - path: /
              service:
                identifier: plex
                port: 80
