# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: plex-media-server
spec:
  interval: 1m
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      # Specify a chart version here for stability, e.g., "0.5.1"
      # Find available versions on Artifact Hub: https://artifacthub.io/packages/helm/gabe565/plex
      version: "0.5.1" # <<--- Specify a version here!
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: plex-media-server
  values:
    # --- Configured Values for gabe565/plex chart ---
    # Based on default values and your requirements.
    # Consult the full chart values.yaml or documentation for advanced options.

    image:
      repository: ghcr.io/linuxserver/plex
      pullPolicy: IfNotPresent
      # tag: "version-1.41.4.9463-630c9f557" # Uncomment and set a specific tag if needed

    env:
      TZ: "Europe/Prague" # <<--- Set your timezone
      # Add other required environment variables here, e.g., PUID, PGID
      # PUID: "1000" # Example PUID - find your user ID on the node
      # PGID: "1000" # Example PGID - find your group ID on the node
      # VERSION: "docker"

    service:
      main:
        type: ClusterIP
        enabled: true
        ports:
          http:
            port: 32400
        #type: LoadBalancer # <<--- Added LoadBalancer service type
        # annotations: {} # Add LoadBalancer specific annotations here if needed (e.g., for MetalLB)
        # For MetalLB, you might need annotations like:
        # annotations:
        #   metallb.universe.tf/address-pool: your-address-pool-name

    ingress:
      main:
        enabled: true # Set to 'false' if you only want the LoadBalancer service
        primary: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # Add other ingress annotations as needed
          # kubernetes.io/tls-acme: "true"
        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: plex
      tls:
        enabled: true # Set to 'false' if you don't want TLS
        secretName: plex-tls # <<--- Name of the TLS secret (ensure it exists)
        cert-manager.io/cluster-issuer: "letsencrypt-production" # Uncomment if using cert-manager
        hosts:
          - plex.${SECRET_DOMAIN}

   