# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: plex-media-server
spec:
  interval: 1m
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      # Specify a chart version here for stability.
      # Find available versions on Artifact Hub: https://artifacthub.io/packages/helm/gabe565/plex
      version: "0.5.1" # <<--- Specify a version here! (Good job setting this!)
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: plex-media-server
  values:
    # --- Configured Values for gabe565/plex chart ---
    # Based on default values and your requirements.
    # Consult the full chart values.yaml or documentation for advanced options.

    image:
      repository: ghcr.io/linuxserver/plex
      pullPolicy: IfNotPresent
      # tag: "version-1.41.4.9463-630c9f557" # Uncomment and set a specific tag if needed

    env:
      TZ: "Europe/Prague" # <<--- Set your timezone
      # Add other required environment variables for linuxserver/plex here
      # PUID and PGID are often required for file permissions
      # Find your user/group ID on the node that will access your media files
      # PUID: "1000" # Example PUID - **UNCOMMENT AND SET THIS**
      # PGID: "1000" # Example PGID - **UNCOMMENT AND SET THIS**
      PUID: "911" # Example PUID - **UNCOMMENT AND SET THIS**
      PGID: "911" # Example PGID - **UNCOMMENT AND SET THIS**

    # hostNetwork is correctly omitted/false here, using standard networking
    # hostNetwork: false

    # dnsPolicy is correctly omitted/defaulting to ClusterFirst
    # dnsPolicy:

    service:
      main:
        enabled: true # <--- Enable the main service
        type: LoadBalancer
        ports:
          http: # This name 'http' corresponds to the port definition below
            port: 32400 # <<--- This is the port Plex uses for HTTP traffic
            # If not specified, it defaults to 'port'. For Plex, 32400 is usually both.
            # targetPort: 32400 # <--- Often explicitly set, though defaults to 'port' if omitted
    persistence:
      config:
        enabled: true # <--- ENABLE THIS FOR PLEX CONFI
        readOnly: false # <--- Plex needs write access
        storageClass: "obenebs-hostpath" # <--- **REPLACE WITH YOUR ACTUAL OPENEBS STORAGE CLASS NAME**
        accessMode: ReadWriteOnce
        size: 10Gi # <--- Adjust size as needed
        retain: true # Recommended to avoid data loss on uninstallt