# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: plex-media-server
spec:
  interval: 1m
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 5m
  chart:
    spec:
      chart: plex
      # Specify a chart version here for stability.
      # Find available versions on Artifact Hub: https://artifacthub.io/packages/helm/gabe565/plex
      version: "0.5.1" # <<--- Specify a version here! (Good job setting this!)
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: plex-media-server
  values:
    # --- Configured Values for gabe565/plex chart ---
    # Based on default values and your requirements.
    # Consult the full chart values.yaml or documentation for advanced options.

    image:
      repository: ghcr.io/linuxserver/plex
      pullPolicy: IfNotPresent
      # tag: "version-1.41.4.9463-630c9f557" # Uncomment and set a specific tag if needed

    env:
      TZ: "Europe/Prague" # <<--- Set your timezone
      PLEX_CLAIM: "" # <<--- Leave empty for first run, or set to your claim tokeno
      # Add other required environment variables for linuxserver/plex here
      # PUID and PGID are often required for file permissions
      # Find your user/group ID on the node that will access your media files
      # PUID: "1000" # Example PUID - **UNCOMMENT AND SET THIS**
      # PGID: "1000" # Example PGID - **UNCOMMENT AND SET THIS**
      PUID: "911" # Example PUID - **UNCOMMENT AND SET THIS**
      PGID: "911" # Example PGID - **UNCOMMENT AND SET THIS**
      VERSION: "docker" # Often required for linuxserver images

    # hostNetwork is correctly omitted/false here, using standard networking
    # hostNetwork: false

    # dnsPolicy is correctly omitted/defaulting to ClusterFirst
    # dnsPolicy:

    service:
      main:
        enabled: true
        ports:
          http: # This name 'http' corresponds to the port definition below
            protocol: TCP # This is the protocol used by the service
            port: 80
            targetPort: 32400 # This is the port your application listens on inside the pod.
            # If not specified, it defaults to 'port'. For Plex, 32400 is usually both.
            # targetPort: 32400 # <--- Often explicitly set, though defaults to 'port' if omitted
        # --- Alternative: Use LoadBalancer Service Type for direct external access ---
        type: LoadBalancer # <<--- Uncomment this AND comment out type: ClusterIP above for a LoadBalancer
        # annotations: {} # Add LoadBalancer specific annotations here if needed (e.g., for MetalLB IP allocation)
        # For MetalLB, you might need annotations like:
        # annotations:
        #   metallb.universe.tf/address-pool: your-address-pool-name
    persistence:
      config:
        enabled: true # <--- ENABLE THIS FOR PLEX CONFI
        type: pvc # <--- Use PVC for OpenEBS
        mountPath: /config # <--- Explicitly set mount path for Plex config
        readOnly: false # <--- Plex needs write access
        storageClass: "obenebs-hostpath" # <--- **REPLACE WITH YOUR ACTUAL OPENEBS STORAGE CLASS NAME**
        accessMode: ReadWriteOnce
        size: 10Gi # <--- Adjust size as needed
        retain: true # Recommended to avoid data loss on uninstall



