# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: utkuozdemir
  namespace: plex
spec:
  interval: 1h
  url: https://utkuozdemir.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  chart:
    spec:
      chart: plex
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir
        namespace: plex
  values:
    image:
      repository: docker.io/linuxserver/plex
      pullPolicy: IfNotPresent
    service:
      controller: plex
      ports:
        http:
          port: 80
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"  # Replace ${SECRET_DOMAIN} with actual domain in your deployment
    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "plex.${SECRET_DOMAIN}"  # Make sure the domain resolves to your service IP
      hosts:
        - host: plex.${SECRET_DOMAIN}  # Make sure this resolves to the correct IP
          paths:
            - path: /
              pathType: Prefix  # Ensure you use a valid pathType like 'Prefix' or 'Exact'
              backend:
                service:
                  name: plex  # Ensure this matches the service name deployed by the Plex chart
                  port: 80
