# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  url: https://k8s-home-lab.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-media-server
spec:
  interval: 1h
  chart:
    spec:
      chart: plex
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex-media-server
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Prague
    service:
      main:
        primary: true
        ports:
          http:
            port: 32400
      dnla-tcp:
        enabled: false
        type: NodePort
        ports:
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
            targetPort: 32469
        externalTrafficPolicy: Local
      dnla-udp:
        enabled: false
        type: NodePort
        ports:
          dnla-udp:
            enabled: true
            port: 1900
            protocol: TCP
            targetPort: 1900
          externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - /
            service:
              name: plex-service
              port: http


    status:
      loadBalancer:
        ingress:
          - ip: 10.101.2.182
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    name: plex
  anotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: "plex.${SECRET_DOMAIN}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: plex-service
            port:
              number: 80
