# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:63vw9Om753pkeM6ngaNt9FZ7gzSUYjuCpgKScHVnKqE=,iv:XAe4PD746/caugTIe0jnfmmm/+VKAj8u/qua+25fzjM=,tag:n4Y0WVMpfnP2/64qUHtOHA==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbXd4OVo2WXFYQXZjaWlF
        VnF1N1ZMNDh3UUdFbjMvWTRHN1FYVmZ5L2tJCmswaWU3dXFyOWVsUUhzVjd0djVP
        cGdQWTB4ZkhmZHZzSzlrSXkweEkxcXMKLS0tIEs2TzlTYVhwakNjWDBzSWU0L2Zm
        TzBBYjlxdVA2TEFsczRNOWluamd5MVkK/dpX+jgn4fUldpt3VXqTH1AqcAtAV6xN
        /xlm/K7y0xgZ3KTSchb2imxVyEx/8G+VHpZ+0SRjQFTdQ5tK0/MB+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-30T14:41:33Z"
  mac: ENC[AES256_GCM,data:DDm9WAPwHrQhIRfwArqD2K717u0v0uHha/etrjP9eoKxWfFUsJjWKbLkSjrhcPfbhZOlv1TS1M220mK7lC4Vo236/6XIcFvpKvf4JcEmcd9A6DA7wlyo5wy/iwUVnf0w1BSa0Wkq4Fjx0ZxG+zVYB72cI7fRHJ2mIapsMb8kuD4=,iv:OX669/ZpzI/WDvbXtlmjzr/1dpNcX4sd90/snbbeeiw=,tag:Kzmk60kr1O9+J68ywjn2Aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
