# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uIESWkZIQbLts6xIh8AJzZYXl0MpAK/B2cQsQoyN/sI=,iv:A84CBhulFqbzBU0itdGMmAy/KD+EjW9AlesjVxBtxbQ=,tag:vPlCYRDtm3h9GqIcfjH4uQ==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajVPTXF1SzN6eTlFYTBF
        RmFwZzVvOXhXcE5iaFN1L3VzdVROMFpLdGcwCkJMaGE1VDdNc09iSUNwcm5TM0x5
        TWdGL0tKRnFqVzlaVHdTOXhlZ1AzTGMKLS0tIEw4RVkrMHRSTmcyTW8wQWMyY0dU
        VTBCdVI4dVI0RTdkQXRqVWRadWpTU1UK92KHE49v1iiVnfc78iY2cNlnOkaKTixl
        YuLSgMhlvqTi9jd3akEN3H3TiYFGlUALTu0SEHg7tJZZoVRIRU242A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T13:07:02Z"
  mac: ENC[AES256_GCM,data:j98+qif3rP/kL+DOB969lA3I3xPyRjw9E0wUwafKPry6kOpv3B8qWvySdEXKVpqQcjFAt418YxhcQXEMkhey72ZtTH9hT9OofxdU4YsbAv2hW63lhs1xuaDvIFeEFBHxb2NFZ8vybEgo5k4laaYySnfkmQnEgXXcf1C3tlemdFs=,iv:GAtsLmpk9prbOU3VQfn0nzoyD92quzlLZOPJiOn+wl8=,tag:a74xl4v1J/CMMftNeaA6QQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
