# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0q8haE5rxkyc6XlMTWt9+AYbLgnDtUIrMCgSadgwl1c=,iv:dXYRTOg2MYz0+RemOL6NWJ7wQXQW02waMBN+eQiIF7A=,tag:DQPgPqpvUYbAQdXy02W3mQ==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRTVJTWxHTTJDeFNRQ25L
        NTZQc3ZEMUR2YlpvSGpHVHdZa3BvR3Z0SnlJCkxLMk9HeVg1Zjg0QmNDMWpoeTlo
        ckZVSEFhYnRyL280VnhUWEV3dW9HQWcKLS0tIEg1a3lSYnNXSVRuZnIycmFUanp2
        Qk0rdUdjUklEVlhrV0dvNmlMeEZkcWsKk+hhvbMDnPjxszbdDflunRW4+7sN6x3f
        Xs7yCtYv3+BYhN18/yo7Zn2dhRqhbWOBE2C8w+eUP5LobXYcBLHIdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T13:17:13Z"
  mac: ENC[AES256_GCM,data:XOVvjDimj9ukcNfZBJKV3hHWbH3kribGoDZvq8aH6sgPMu/FuLis98TMCC3tDLYcxoaJqvp0lEZBq3N0VbwUPv02/H5UczgtbToDBMGuBNzquatGFQaXtd20/NhtdAnSdEmJFZG1d2mDfRjbNnEtsnmQdd5MNhzXQLq6bq/Mzc8=,iv:fprWUkjptWYydKARm1PiZEMqITrxv+FJT3BTLRi+Oz0=,tag:CYetGKBvY0qx28bJ8QDZgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
