# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0CaURx+OsdiMmyU6RI146jxHVUVld3tyhaiFioTtDzw=,iv:AIHNWbVmHxXzKiSwoskmOz6a2Ts/eKiNvzwiM4Il6kU=,tag:avvrZYQ+I8P+1FrdpuPKxA==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYlltQ2thUlRoSEtZcHEz
        NFBHam42R1psZURHNGw4TnYxRXpKUitJa0VzClZlazgxeVF1d2prTkV4T2VSYWF6
        SGFUV2ozOTNoUHZyaEZvcjV4a0N3M1kKLS0tIFBrV0ZFS0ZxTW9DT1VET2ZzSjll
        Uk1hM284M2k3VHJYZ2VhUWQzSkdEaUkK6xXZKSZ690OmB+eFJUpDIOto06XR8fIz
        5ZBSmipSCBr/Wt+fLBQNbS5T56bHMgItmkTt5jqUvMgz/NWIM4Y57w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T09:31:28Z"
  mac: ENC[AES256_GCM,data:9z33/4t5Nu3GFLt0DpCcA6WOJ2+UEdMOm0HOwDihsT7eSBIrb5aDWHDUTGmlkJ+OxrgPYMG7RFM4fyjc3Bi1n0a2yotLK8BkLuR4LFYE76YGeOMPkk73CH4Xw4nGbavWNfqqci9txGLovxdXrEYo+7oP+wXnT3fVwTZKKhiV9/0=,iv:GT+hc8j1z0T9cVJvOVdl8/bh/hU8gyNIQPjmB2wTBp0=,tag:k9pxd4qmAaWxs8H9xBGfEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
