# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3OoSVbyUaxDtOHn1jpMzDBnHt0GbTpYMy/9xuz4pWrE=,iv:Dh6yQgws1fTSpheHF2wEigttNLGJAlYWZsGN4kbDnac=,tag:0APPZXk14LNdsoIhTSDfaQ==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNkFQTkdRYk9odm43REhu
        Y3ZwVmZXNFRrb0Fnay9Udjc3WFMzTHRBUFhJCmU3SFhmSnMyMFM5bFJRdmVWTUkx
        UXBEOVBoQTc3OTRqcjJrdXRyUTF5bzAKLS0tIG1CUkRHS0oySlJFQWwvMjgxMWlj
        dmRGSnhWU0hkL1ZJOUs2d2NNOU1WcXcK8q0ZmmNe8brC91eeqeFyQ7lqtQNJBBKw
        PIjrPh5JSzLkZ9ul1yZbSdwp0lOVyvCO52x0qRyhDMALB+57qCdCFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-30T15:10:24Z"
  mac: ENC[AES256_GCM,data:GJZ1HIF4EV7YiTabvPC5ZqY8WmBMZzvwEHge2wwSWxS/lyakBZPH9gyJpLxVi04G+7mfrxSQx0hugj8J6Zv7kGi2tmNBe/7ECnLluzZLDEgKtQZSshtvJlIqLZkiiltQz5wIZqUZKrDzOBpUCsfvdrpmrCHIU0Z2kNgGLpY9UrQ=,iv:ZpciHA99G2XAhPGgb+sV8g0uiQ9PGQK/bd7dU0sh/yE=,tag:EyD2XtIYzeD7StwAVssS0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
