# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5wMFQLlT2s6wnsCch/5Ana6OIn3dt3gRO4yGipoCnBEUg3csKFikcw==,iv:pVPGBDJf4FBZdr0oaj01f299yY4Ejwn+Ymcfia5qGQo=,tag:ffzAXGM/bxuCZKlR84MQOg==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL2ZBYkxiL3ppM3ZqT2Ez
        a1lRUTdhK3hESmpWNXo1cDFvOFQxd0V4blZ3ClpxU3RJaE0vRHNtZVpJQzVKNEpK
        b3pIOFNNaWdnNDI5Z0s4WDRzNmtrdU0KLS0tIHVWdWk0TXdraS9NMVR2cWZpWG1E
        SUxsSmlOYTlzdmkvK3Nja3JjNnowOHcKSoe2Y11a5RG747Eub8Ejh2jp0fVPbwmt
        sT5g8ZCih5gusHp7FCxA32H4n3Mn6R1TgDYTKKC4M8JsaeFeJ5p27A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-30T15:10:24Z"
  mac: ENC[AES256_GCM,data:+nem7UHBIsuDZAnC5sMUeznLdDxLH4gWeFiP3D5f+AFscY2iN+zdt5YYVa/ZhbOjlkarSQzh3Us9PxXb+pJD7isLvqguNBpznKiW9/Gf59keDeyW0LQh9nxl0bUdoYQc9zsgk0n4c9H4plqnEH91aMTy2W6GNKAjgZUazS0nG8I=,iv:iE0V55vtkbxEnEvHzggdps1w+HFkYvIIAlBR5Y/BkiM=,tag:jjZfFOrRbkU7n+ITTUpVCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
