# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gbJveQn721nVFydJyVxIEpnMnW+queGAvBXgIbZdGh7UbCRfWadenA==,iv:Y6O57d1pu6QNt3FLqI0i0Cwz9V1Nz9awOfFTq0+FJqQ=,tag:V3b5bSBBUJKHCvk6Bd/swA==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RC9KM3NkRSsxL2xQYUY1
        SkdjdW5XZEFyU2xqQUVhcjR3WEJvcERGeHk4CisxckhrdDB1aXBSWTlDcDFoMEV3
        ZENHSkgyZWw3UjR5SHJrRGxpUjBYaVEKLS0tIElpMHMwRUcxOHRvMG9ZTnlRVzdp
        WVRVbk1VeEgxTjRtU2l5R3o0WFBaZDQK8kZ/1WrkKJSMFrj10xllwIXoF0fdYWET
        S/M1vGAutw9wwOIE0LUQfbBLtWYQFry5s+FF96XgdQ4YZRgJsd2WQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T09:28:11Z"
  mac: ENC[AES256_GCM,data:fV4/xLuKjPMynN7IUrnN6lSuHyuChH0c22el3tMhhnOeNSa1DG08TFT5+Eym+X7shdEOjcZS2SG/mwU20PIjk3RUpSQMetQg4IieNqfqzqHX8ORaSfNvgrveXrpYvTvRnDFpLYKlozY2AQt5ekBalp2U+QjrbFzODllJK0iGVHg=,iv:l0PoHJ1aIV+tJB4/LPJ0CKxE8RQOO9G30sXe5OwRjow=,tag:DUioIj1ZhIA+zslxgbiD5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
