# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hW1QjO76ED1v7bRB3KEidJa2w/klcRKoWe++sPjZ05v6N3zUGEnljg==,iv:YpXffSnV6YDt8S3G1049+FZzjMEH7u+VE0/yer3BGQg=,tag:qcmTUd7JJL03FOB2mbp76w==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVTJPL1pnOFJ4Sk5Fd0pC
        RHk2OVd4TWRNRDIwb096SkMxUC91UnU5VGdjCmZvbXVZQW1aT0dIcUlRbG1SZ3pQ
        SE16VFFuNkpsQjJGck85cjVvclRoa2cKLS0tIFFoWFpkMkVtOHg2R2NBWUx4Vjdh
        ZTJaOGdzNWgvT1huVVZ4cjkrVEVWc3MKZNMEzX3IIpOP20tQWhr6bf6dufIKdoFf
        41fVLA6nXaAF5h9xjph3vUEkpect0SltjAnPauOrAe2vbZ+Xivf5xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T09:31:28Z"
  mac: ENC[AES256_GCM,data:xk5gI3BCVu+mKfrUDw5/IoZpY31388/8vyLFSqV7PGd5ec0CFKDY40amNYxuM+bRAI7sPzYXSjHviKnDNvpz3V+g8pT2y+QmQF6GKXPSRX85yrYJs1jmUC5lmEcqu4ul5Stolrx+fxKRy+OnEe1bbNRh7cq0I8u0nmVYomPEypY=,iv:wm5SfSQd8j81YyA9k50O5EDa8Cqid7zBnbQqX+PI86I=,tag:stpBVhI9j0N9DpSi48dHhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
