# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:eTbEGP/zw9WwARV6OtFcB4ThecgYvENVwEejKbmsyXTyOhXu6TVQ8g==,iv:lRNv+YqYVF5mxyVHyOijGVjYffqJ0CI3Fid3+6eQcp0=,tag:nM4IKkqFgPVdQ2x10sjYvQ==,type:str]
sops:
  age:
    - recipient: age1jncxge0k7j7gcxdt0jd86uuhxamvmz55q3lja27pwlduyc4n752s7lzxeq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUIxRW5vWUVrYW4rWEl6
        T1hYMDlHM1E5ZmtMTWoyZ28zZHU5RjUvemdzCk01b05ENGxNMWhoTjVMQzJPd3hL
        aWU3MDU4RWVYSXgwamQ0aGlTZTNLY1UKLS0tIG1HUmtnTDU1TVN4dXNEQjlZN2lj
        QWhKaXFXVzhiSm9VOWZJNlRtdUxhajAKuXGJdwiOsNi1BtDzFy+YpROCLnE4SMYK
        oYnZRFCCt0pPg/3/QA6/B/oA3os+iKmueikEcfCG8DFCQqr3sg5olQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T13:17:13Z"
  mac: ENC[AES256_GCM,data:wjk7jSvD2Z3jrDmCwy0TN6T4yRG0QZCBPVMXeX56FOF94SG2qgsLXJv3bgUcaKxdt97dHtPPYDhEYc1wHHleYJ0O8dwlR9szQEf1b7avDA3Aw9ksemhuZeLDlvweuKX4bgBPITvQh+AG92HpsUfK3of1bp1ZHoUzevs52zEr7qA=,iv:blhhsWVnKFg3Hk5MUAbdzxyTFCP/wpk9NyzPlSP899M=,tag:+FltL8i7dv1Tp8aL2fnAAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
