---
name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    name: Scan for Secrets with TruffleHog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
